_schema: _schema
paths:
  uploads: uploads
  static: ''
  dam_uploads: ''
  dam_static: ''
  collections: ''
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  pages:
    path: ''
    icon: notes
    output: true
    filter: strict
    description: ''
    _editables:
    _inputs:
    _select_data:
    _structures:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default page:
        path:
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon: notes
        preview:
        _editables:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
_inputs:
  layout:
    type: text
    hidden: true
    cascade: true
  col-type:
    type: text
    hidden: true
    cascade: true
  block-content-html:
    type: html
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      center: text-center
      format: p h2 h3 a img
      bulletedlist: true
      numberedlist: true
      horizontalrule: true
      image: true
      image_size_attributes: true
      link: true
      resize_style: contain
      snippet: false
      styles: /editor.css
    label: Content
    cascade: true
  pre-heading-style:
    type: select
    options:
      allow_empty: true
      values:
        - style 1
        - style 2
        - style 3
    cascade: true
  heading-style:
    type: select
    options:
      allow_empty: true
      values:
        - style 1
        - style 2
        - style 3
    cascade: true
  sub-heading-style:
    type: select
    options:
      allow_empty: true
      values:
        - style 1
        - style 2
        - style 3
    cascade: true
  content:
    type: markdown
    options:
      allow_resize: true
      allow_custom_markup: false
      remove_custom_markup: false
      initial_height: 320
      center: text-center
      format: p h2 h3 a img
      horizontalrule: true
      image: true
      image_size_attributes: true
      left: text-left
      link: true
      resize_style: contain
      right: text-right
      snippet: true
      styles: /editor.css
    label: Content
    cascade: true
  min-height:
    type: select
    options:
      allow_empty: true
      values:
        50vh: half screen min-min
        75vh: three quater screen min-min
        90vh: just short of full screen
        100vh: full screen
    cascade: true
  text-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - center
        - right
    cascade: true
  desktop-image-position:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - right
    cascade: true
  vert-alignment:
    type: select
    options:
      allow_empty: false
      values:
        - top
        - middle
        - bottom
    cascade: true
  top-space-padding:
    type: number
    cascade: true
    unit: vh
    option:
      min: 0
      max: 100
      step: 1
  bottom-space-padding:
    type: number
    cascade: true
    unit: vh
    option:
      min: 0
      max: 100
      step: 1
  img_aspect:
    type: select
    options:
      allow_empty: false
      values:
        - Square
        - Tall Portraight
        - Portraight
        - Landscape
        - Wide Landscape
        - Extra Tall
    cascade: true
  video-orientation:
    type: select
    options:
      - vertical
      - horizontal
    cascade: true
  float-direction:
    type: select
    options:
      allow_empty: false
      values:
        - left
        - right
    cascade: true
    default: left
_structures:
  blocks:
    style: modal
    values:
      - label: Text banner
        picker_preview:
          text: Simple banner
          subtext:
          icon:
          icon_color:
          image:
          metadata:
          gallery:
            image: /uploads/banner-preveiw.png
            icon:
            icon_color:
            fit:
        tags:
        value:
          _id: banner
          block-content-html: <h2> banner heading </h2> <p> subtext </p>
          background-desktop-image: 
          background-mobile-image: 
          text-alignment: center
          vert-alignment: middle
          overlay-color: '#000000'
          overlay-opacity: 0.5
          min-height: 90vh
          top-space-padding: 10
          bottom-space-padding: 10
          color-scheme: leaf-100
      - label: Text & image grid
        picker_preview:
          text: text and grid
          subtext:
          icon:
          icon_color:
          image:
          metadata:
          gallery:
            image: /uploads/split-grid-preview.png
            icon:
            icon_color:
            fit:
        tags:
        value:
          _id: banner-split
          block-content-html:
          background-desktop-image: https://picsum.photos/id/1023/600/400
          background-mobile-image: https://picsum.photos/id/1024/600/400
          background-alt: 
          desktop-collapse-bg-padding: true
          desktop-image-position: right
          section-gap: 1rem
          text-alignment: center
          vert-alignment: bottom
          mobile-image-position: bottom
          mobile-collapse-bg-padding: false
          img_aspect: Square
          top-space-padding: 2
          bottom-space-padding: 2
          color-scheme: leaf-500
      - label: Video banner
        picker_preview:
          text: Video banner
          subtext:
          icon:
          icon_color:
          image:
          metadata:
          gallery:
            image: /uploads/split-grid-preview.png
            icon:
            icon_color:
            fit:
        tags:
        value:
          _id: banner-video
          block-content-html:
          videos:
            - video_path: /uploads/sea-24216-360p.mp4
              video_type: mp4
          controls: false
          autoplay: true
          text-alignment: center
          vert-alignment: middle
          overlay-color: black
          overlay-opacity: 0.5
          min-height: 90vh
          top-space-padding: 10
          bottom-space-padding: 5
          color-scheme: leaf-500
      - label: youtube banner
        picker_preview:
          text: youtube banner
          subtext:
          icon:
          icon_color:
          image:
          metadata:
          gallery:
            image: /uploads/banner-preveiw.png
            icon:
            icon_color:
            fit:
        tags:
        value:
          _id: banner-youtube
          block-content-html: <h2> Simple heading </h2>
          text-alignment: right
          embed_code: <iframe width="560" height="315" src="https://www.youtube.com/embed/81vugfyEt5E?si=9tavipgzzvGWmnln" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
          color-scheme: leaf-300
      - label: text block
        picker_preview:
          text: text block
          subtext:
          icon:
          icon_color:
          image:
          metadata:
          gallery:
            image: /uploads/banner-preveiw.png
            icon:
            icon_color:
            fit:
        tags:
        value:
          _id: text-block
          block-content-html:
          text-alignment: center
          color-scheme: leaf-100
          max-width:
      - label: Clickable slider
        picker_preview:
          text: Slider
          subtext:
          icon:
          icon_color:
          image:
          metadata:
          gallery:
            image: /uploads/slider-preview.png
            icon:
            icon_color:
            fit:
        tags:
        value:
          _id: slider
          block-content-html: <h2> Slider heading </h2><h3>  with subheading  </h3>
          text-alignment: right
          text-box-max-width: 500px
          img_aspect: Square
          slider_column_count: 3
          slider_col_color_scheme: leaf-500
          slider:
            - block-content-html: <h3> lorem </h3><h2>  experiences  </h2>
              youtube_embed:
              image: 
              link: leaf-500
            - block-content-html: <h3> lorem </h3><h2>  experiences  </h2>
              youtube_embed:
              image: 
              link: leaf-500
            - block-content-html: <h3> lorem </h3><h2>  experiences  </h2>
              youtube_embed:
              image: 
              link: leaf-500
            - block-content-html: <h3> lorem </h3><h2>  experiences  </h2>
              youtube_embed:
              image: 
              link: leaf-500
          color-scheme: leaf-500
      - label: Grid
        picker_preview:
          text: grid
          subtext:
          icon:
          icon_color:
          image:
          metadata:
          gallery:
            image: /uploads/grid-preview.png
            icon:
            icon_color:
            fit:
        value:
          _id: grid
          block-content-html: >-
            <h3 class="sub-heading"> OUR HOLISTIC APPROACH </h3> <h2
            class="heading">A personalised wellness retreat, tailored to you.
            </h2>
          text-alignment: center
          grid-desktop-columns: 4
          grid-mobile-columns: 2
          grid-gap: 1rem
          col-internal-padding: true        
          img-mixed-aspect: false
          columns:
          color-scheme: leaf-500
      - label: html block
        value:
          _id: liquid-block
          liquid_code: >-
            <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3944.494647487761!2d115.12809509999998!3d-8.6444149!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2dd247a13066d977%3A0x467f2ebcb0fb76ef!2sHair%20by%20therapy!5e0!3m2!1sen!2sau!4v1726985453546!5m2!1sen!2sau"
            width="600" height="450" style="border:0;" allowfullscreen=""
            loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
          cape-width: true
          vertical-padding: true
          color-scheme: leaf-300
      - label: Scrolling grid
        tags:
        value:
          _id: horizontal-scroll-basic
          block-content-html: <h3> lorem </h3> <h2>  experiences  </h2>
          image-width: 250px
          img_aspect: Square
          scroll-items:
            - heading: first
              image: https://picsum.photos/id/684/1200/630
              description: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                corporis obcaecati doloremque optio! Unde accusantium, esse
                consectetur asperiores voluptates obcaecati nobis libero
                necessitatibus vero labore quod eaque. Illum, tenetur alias!
              link:
            - heading: second
              image: https://picsum.photos/id/684/1200/630
              description: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                corporis obcaecati doloremque optio! Unde accusantium, esse
                consectetur asperiores voluptates obcaecati nobis libero
                necessitatibus vero labore quod eaque. Illum, tenetur alias!
              link:
            - heading: third
              image: https://picsum.photos/id/684/1200/630
              description: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                corporis obcaecati doloremque optio! Unde accusantium, esse
                consectetur asperiores voluptates obcaecati nobis libero
                necessitatibus vero labore quod eaque. Illum, tenetur alias!
              link:
            - heading: fourth
              image: https://picsum.photos/id/684/1200/630
              description: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                corporis obcaecati doloremque optio! Unde accusantium, esse
                consectetur asperiores voluptates obcaecati nobis libero
                necessitatibus vero labore quod eaque. Illum, tenetur alias!
              link:
          color-scheme: leaf-100
      - label: Scrolling grid with inline text box
        tags:
        value:
          _id: horizontal-scroll-inline-text-box
          block-content-html: <h3> lorem </h3> <h2>  experiences  </h2>
          text-box-width: 350px
          image-width: 250px
          img_aspect: Square
          scroll-items:
            - heading: first
              image: https://picsum.photos/id/684/1200/630
              description: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                corporis obcaecati doloremque optio! Unde accusantium, esse
                consectetur asperiores voluptates obcaecati nobis libero
                necessitatibus vero labore quod eaque. Illum, tenetur alias!
              link:
            - heading: second
              image: https://picsum.photos/id/684/1200/630
              description: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                corporis obcaecati doloremque optio! Unde accusantium, esse
                consectetur asperiores voluptates obcaecati nobis libero
                necessitatibus vero labore quod eaque. Illum, tenetur alias!
              link:
            - heading: third
              image: https://picsum.photos/id/684/1200/630
              description: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                corporis obcaecati doloremque optio! Unde accusantium, esse
                consectetur asperiores voluptates obcaecati nobis libero
                necessitatibus vero labore quod eaque. Illum, tenetur alias!
              link:
            - heading: fourth
              image: https://picsum.photos/id/684/1200/630
              description: >-
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab
                corporis obcaecati doloremque optio! Unde accusantium, esse
                consectetur asperiores voluptates obcaecati nobis libero
                necessitatibus vero labore quod eaque. Illum, tenetur alias!
              link:
          color-scheme: leaf-100
      - label: Accordion
        value:
          _id: accordion
          block-content-html: <h2 class="heading-lg"> FREQUENTLY ASKED QUESTIONS </h2>
          drop_down:
            - button-text: question that you might have
              block-content-html: <p>answer to that question </p>
          color-scheme: 
      - label: Timeline
        tags:
        value:
          _id: timeline
          block-content-html:
          color-scheme: leaf-100
          max-width-timeline:
          time-line-points:
            - heading:
              paragraph:
      - label: Ticket banner
        value:
          _id: ticket-banner
          banner_speed_in_px: 50
          banner_message:
            - text: floating message
              url:
            - text: clickable message
              url: google.com
          color-scheme: leaf-500
      - label: Text & image grid with experience feilds
        picker_preview:
          text: text and grid with experience feilds
          subtext:
          icon:
          icon_color:
          image:
          metadata:
          gallery:
            image: /uploads/split-grid-preview.png
            icon:
            icon_color:
            fit:
        tags:
        value:
          _id: banner-split-experience-specific
          block-content-html:
          size: 40m2
          bed: KING
          type: Pool Suite
          background-desktop-image: https://picsum.photos/id/1023/600/400
          background-mobile-image: https://picsum.photos/id/1024/600/400
          background-alt: 
          desktop-collapse-bg-padding: true
          desktop-image-position: right
          section-gap: 1rem
          text-alignment: center
          vert-alignment: bottom
          mobile-image-position: bottom
          mobile-collapse-bg-padding: false
          img_aspect: Square
          top-space-padding: 2
          bottom-space-padding: 2
          color-scheme: leaf-500
  columns:
    style: modal
    values:
      - label: Image
        value:
          col-type: img
          image: https://picsum.photos/id/1023/600/400
          image_alt:
          img_aspect: Square
          col-width: 2
          col-height: 2
          hide-on-mobile: false
          mobile-first: false
          image-position: 50% 50%
      - label: Text Block
        value:
          col-type: text
          block-content-html:
          text-alignment: center
          vert-alignment:
          icon-path:
          icon-alt:
          color-scheme: leaf-300
          col-width: 1
          col-height: 1
          hide-on-mobile: false
          mobile-first: false
      - label: video
        value:
          col-type: video
          videos:
            - video_path: /uploads/sea-24216-360p.mp4
              video_type: mp4
          video_controls: false
          video_autoplay: false
          img_aspect: Square
          col-width: 1
          col-height: 1
          hide-on-mobile: false
          mobile-first: true
  header_links:
    style: modal
    values:
      - label: simple link
        value:
          text: home
          link: /
      - label: link with sublinks
        value:
          text: home
          link: /
          sub_links:
            - text: sublink 1
              link: /
            - text: sublink 2
              link: /
            - text: sublink 3
              link: /
timezone: Etc/UTC
_snippets_definitions:
  jekyll_liquid_format:
    root_value_delimiter: '='
    root_pair_delimiter:
      - ''
    array_boundary:
      start: '['
      end: ']'
    array_delimiter: ','
    string_boundary:
      - '"'
      - ''''
    forbidden_tokens:
      - '%}'
      - '-%}'
      - '}}'
      - ','
_snippets_templates:
  jekyll_liquid_include:
    snippet: '{% include [[name]] [[args]] %}'
    params:
      name:
        parser: literal
        options:
          literal:
            ref: include_name
      args:
        parser: key_values
        options:
          models:
            ref: named_args
          format:
            ref: jekyll_liquid_format
_snippets:
  image_grid:
    template: jekyll_liquid_include
    inline: false
    preview:
      text: 3 image gallery
    definitions:
      include_name: snippets/imgGallery3.html
      named_args:
        - editor_key: first-image
          type: string
        - editor_key: first-alt
          type: string
        - editor_key: second-image
          type: string
        - editor_key: second-alt
          type: string
        - editor_key: third-image
          type: string
        - editor_key: third-alt
          type: string
        - editor_key: image_size_ratio
          type: string
  floating_image:
    template: jekyll_liquid_include
    inline: true
    preview:
      text: floating image
    definitions:
      include_name: snippets/image-float.html
      named_args:
        - editor_key: image
          type: string
        - editor_key: alt
          type: string
        - editor_key: float-direction
          type: string
        - editor_key: max-width
          type: string
